apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ultimate-devops-servicemonitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ultimate-devops-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
