apiVersion: v1
kind: Service
metadata:
  name: ultimate-devops-service
spec:
  type: NodePort
  selector:
    app: ultimate-devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
